"""
FastAPI wrapper around the orchestrator -- exposes the pipeline as a real
HTTP service instead of only a script you run from the command line.

Run with: uvicorn api:app --reload
Then visit http://127.0.0.1:8000/docs for interactive API docs (auto-generated by FastAPI).
"""
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional
from dotenv import load_dotenv

load_dotenv()  # reads .env in this folder if present -- see .env.example

from orchestrator import Orchestrator

app = FastAPI(
    title="SOC-Agent API",
    description="Multi-agent security incident response pipeline. NOTE: this is a portfolio/demo project evaluated on a public academic benchmark (NSL-KDD) -- not a production security product.",
    version="1.0.0",
)

orchestrator = Orchestrator()


class AlertRecord(BaseModel):
    duration: float = 0
    protocol_type: str = "tcp"
    service: str = "http"
    flag: str = "SF"
    src_bytes: float = 0
    dst_bytes: float = 0
    land: int = 0
    wrong_fragment: int = 0
    urgent: int = 0
    hot: int = 0
    num_failed_logins: int = 0
    logged_in: int = 0
    num_compromised: int = 0
    root_shell: int = 0
    su_attempted: int = 0
    num_root: int = 0
    num_file_creations: int = 0
    num_shells: int = 0
    num_access_files: int = 0
    num_outbound_cmds: int = 0
    is_host_login: int = 0
    is_guest_login: int = 0
    count: int = 1
    srv_count: int = 1
    serror_rate: float = 0
    srv_serror_rate: float = 0
    rerror_rate: float = 0
    srv_rerror_rate: float = 0
    same_srv_rate: float = 1
    diff_srv_rate: float = 0
    srv_diff_host_rate: float = 0
    dst_host_count: int = 1
    dst_host_srv_count: int = 1
    dst_host_same_srv_rate: float = 1
    dst_host_diff_srv_rate: float = 0
    dst_host_same_src_port_rate: float = 0
    dst_host_srv_diff_host_rate: float = 0
    dst_host_serror_rate: float = 0
    dst_host_srv_serror_rate: float = 0
    dst_host_rerror_rate: float = 0
    dst_host_srv_rerror_rate: float = 0


@app.get("/")
def root():
    return {
        "service": "SOC-Agent API",
        "status": "running",
        "note": "Demo/portfolio project -- see /docs for interactive API, /health for status",
    }


@app.get("/health")
def health():
    return {"status": "ok", "model_loaded": orchestrator.triage_agent.model is not None}


@app.post("/analyze")
def analyze_alert(record: AlertRecord):
    """
    Runs a network connection record through the full pipeline:
    Triage -> Investigation (if threat) -> Containment (if threat).
    Returns the verdict, evidence, actions taken, and timing.
    """
    try:
        result = orchestrator.process_alert(record.model_dump())
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/incident/{incident_id}")
def get_incident_trail(incident_id: str):
    """Returns the full audit trail for a given incident ID."""
    trail = orchestrator.get_audit_trail(incident_id)
    if not trail:
        raise HTTPException(status_code=404, detail="Incident not found")
    return {"incident_id": incident_id, "trail": trail}
